s4 := SymmetricGroup(4);;
SetName(s4,"s4");
GraphicSubgroupLattice(s4);
a4 := AlternatingGroup(4);;
SetName(a4,"a4");
GraphicSubgroupLattice(a4);
v4 := Group([(1,2)*(3,4), (1,3)*(2,4)]);;
v4 := Elements(v4);
P0 := Group([(1,2,3)]);;
P0 := Elements(P0);
Subgroups := ConjugacyClassesSubgroups(a4);
Subgroups[3];
P1 := Representative(last);
IsSubgroup(a4, P0);
IsSubgroup(a4, P1);
P1 := Elements(P1);
Set(a4, x -> Elements(x*P0));
Elements(P0*(1,2)*(3,4));
Elements(P1*(1,2)*(3,4));
