<?xml version="1.0"?>
<algebra>
<basicAlgebra>
<algName>C2 x C2</algName>
<desc>C2 x C2. 0 = id, 1 = f1, 2 = f2, 3 = f1*f2.</desc>
<cardinality>4</cardinality>
<operations>
<op>
<opSymbol><opName>p</opName>
<arity>2</arity>
</opSymbol>
<opTable>
<intArray>
<row r="[0]">0,1,2,3,</row>
<row r="[1]">1,0,3,2,</row>
<row r="[2]">2,3,0,1,</row>
<row r="[3]">3,2,1,0,</row>
</intArray>
</opTable>
</op>
</operations>
</basicAlgebra>
</algebra>
